- src/util/index.ts
- src/util/resources.ts
Also added conditions for the text rendering based on if the link opens in new tab or the same tab.
> Added screenreader text for links opening in new tab

- README.md
- package.json
- src/util/index.ts
- src/util/resources.ts
Made SR-text for links optional and added checks if it exists
> Fixed error caused by resource text

- CHANGES
- package.json
- src/util/index.ts
This was done to fix trusted types error
> Returning trusted types in sanitize functions where it was missing

- package-lock.json
- package.json
- src/components/__tests__/choice-spec.tsx
- src/components/__tests__/componentsWithChildren-spec.tsx
- src/components/__tests__/help-spec.tsx
- src/components/__tests__/hidden-spec.tsx
- src/components/__tests__/markdown-spec.tsx
- src/components/__tests__/open-choice-spec.tsx
- src/components/__tests__/utils.ts
- src/components/formcomponents/open-choice/open-choice.tsx
Display valueString text in data-receiver
> Bug: Open-choice radiobutton 

- CHANGES
- package.json
- src/components/formcomponents/date/date-day-input.tsx
Adding checks to avoid setting date to an invalid date
> Bugfix: invalid date moment

- CHANGES
- package.json
- src/components/index.tsx
When repeat item is group do not disabled repeat button
> Bug empty field in repeat group

- CHANGES
- package.json
- src/actions/newValue.ts
- src/components/__tests__/__data__/scoring/code-scoring/index.ts
- src/components/__tests__/__data__/scoring/code-scoring/q.json
- src/components/__tests__/scoring-spec.tsx
- src/components/formcomponents/decimal/decimal.tsx
- src/components/index.tsx
- src/constants/scoring.ts
- src/util/index.ts
- src/util/scoring.ts
- src/util/scoringCalculator.ts
Section score, Total score and calculated extension can be displayed in item with type Decimal or Integer, in addition to Quantity
> Score and calculated extension

- CHANGES
- package-lock.json
- package.json
- src/components/__tests__/__data__/scoring/fhirpath-score/q.json
- src/components/__tests__/scoring-spec.tsx
- src/components/index.tsx
- src/types/state.ts
- src/util/scoringCalculator.ts
Total Scoring (TS) does not include calculated fields in its calculation.
TS only calculates Section Score (SS)
> Scoring Del 2

- src/util/index.ts
- Removed trustedTypes because this created issues in HN-Skjema when rendering empty translations in sidebar
> remove trusted types on empty string

- CHANGES
- package-lock.json
- package.json
forgot to bump the version in the last pr
> bump to 13.2.2

- package-lock.json
- package.json
Removes beta from refero versjon in package.json
> Removes beta from refero versjon in package.json

- CHANGES
- package.json
- src/components/formcomponents/choice/choice.tsx
- src/components/formcomponents/choice/slider-view.tsx
- src/components/formcomponents/open-choice/open-choice.tsx
added rendering of children to slider component
> Slidercomponent not rendering children

- CHANGES
- package-lock.json
- package.json
- src/components/formcomponents/attachment/__tests__/attachment-spec.tsx
- src/components/formcomponents/attachment/attachment.tsx
- src/components/formcomponents/attachment/attachmentUtil.ts
- src/components/formcomponents/attachment/attachmenthtml.tsx
- src/components/formcomponents/attachment/mockUtil.tsx
- src/constants/extensions.ts
- src/util/extension.ts
Fix on attachment file size: Rules: 1) Questionnaire Item max rules 2) Props 3) Refero Constant
> Bug fix: Attachment max file size validation

- CHANGES
- package-lock.json
- package.json
- src/components/__tests__/__data__/scoring/code-scoring/q.json
- src/components/__tests__/scoring-spec.tsx
- src/constants/scoring.ts
- src/util/scoring.ts
Bug: Calculation working in item with RenderOptions
> Bug: Calculation RenderOptions

- src/components/__tests__/slider-spec.tsx
- src/components/formcomponents/choice/slider-view.tsx
Added helpermethods in slidercomponent for supporting emojis as html codes, unicode, hex and decimal values
> Support for emojis as codes for slider

- CHANGES
- package-lock.json
- package.json
- src/components/formcomponents/table/tables/table-hn2/TableHn2.tsx
- src/components/formcomponents/table/tables/table-hn2/utils.ts
- fixed a bug related to sorting on column with index 0.
> fix a small bug with sorting hn2

- .github/workflows/build.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
added two new scripts and removed one. 
seperated the release and prerelease script for refero
> Update github actions  

- package-lock.json
- src/components/createQuestionnaire/GenerateQuestionnaireComponents.tsx
- src/components/formcomponents/date/__tests__/date-time-spec.tsx
- src/components/formcomponents/date/date-year-input.tsx
- src/components/formcomponents/table/tables/constants.ts
- src/components/formcomponents/table/tables/utils.ts
- Fix dates not showing in tabels
> remove safeparse for dates

- src/components/createQuestionnaire/ResponseItem.tsx
- src/components/validation/__tests__/validation-summary-utils-spec.ts
- src/components/validation/utils.ts
- src/util/refero-core.ts
- src/validation/__tests__/defaultFormValues-spec.ts
- update id in item creator
- added some tests
> fix id that broke test

- CHANGES.md
- package.json
- src/components/formcomponents/repeat/RenderRepeatButton.tsx
- src/reducers/form.ts
- src/util/__tests__/refero-core-spec.ts
- src/util/refero-core.ts
A repeatable group becomes active when an item in the group has answer.
> Activation of a repeatable Group 

- src/components/__tests__/componentsWithChildren-spec.tsx
- src/components/__tests__/copy-from-spec.tsx
- src/components/__tests__/hidden-spec.tsx
- src/reducers/form.ts
- src/util/__tests__/__data__/valuesets/valueset-8459/group-repeatable-answer.json
- src/util/__tests__/__data__/valuesets/valueset-8459/group-repeatable.json
- src/util/__tests__/__data__/valuesets/valueset-8459/index.ts
- src/util/__tests__/refero-core-spec.ts
QuestionnaireResponse updates after an attached file has been deleted
> Bug: Can remove an attached file

- preview/FormFillerPreview.tsx
- src/components/formcomponents/attachment/__tests__/__data__/mockUtil.tsx
- src/components/formcomponents/attachment/__tests__/attachment-spec.tsx
- src/components/formcomponents/attachment/attachmenthtml.tsx
- src/util/attachmentHelper.ts
- Validates file format, maximum file size and maximum total files can be attached
- Selects several files if attachment is repeatable
- Deactivate add file button if attachment is not repeatable and one file is uploaded already
> Bug: attachment validation, add file button, select several file

- preview/FormFillerPreview.tsx
- src/components/formcomponents/attachment/attachment.tsx
- src/reducers/__tests__/newValueAction-spec.ts
- src/reducers/form.ts
A attached file can be deleted by title as FileId
> Bug: Can delete an attached file

- CHANGES.md
- package.json
- src/components/formButtons/formButtons.tsx
- src/components/renderForm.tsx
- src/types/formTypes/formButton.ts
- src/types/referoProps.ts
- src/util/resources.ts
* Microweb step modifications
* Custom props and callbacks for navigation buttons when using isMIcrowebStep= true
> Microweb step modifications

- .github/dependabot.yml
- .gitignore
- package-lock.json
- package.json
- vite.config.ts
Adds dependabot to the repository
> dependabot

- src/components/index.tsx
- Change default mode to onTouched
> change default mode

- src/components/formcomponents/group/table/tables/table/StandardTable.tsx
- src/components/formcomponents/group/table/tables/table/StandardTableHeader.tsx
- src/components/formcomponents/group/table/tables/table/utils.ts
- Show all header values in standard table
- Fix bug with useEffect infinite loop
> Display all header values in standard table

- src/components/formcomponents/group/table/tables/gtable/__tests__/GTable-spec.tsx
- src/components/formcomponents/group/table/tables/table/StandardTable.tsx
- src/components/formcomponents/group/table/tables/table/StandardTableHeader.tsx
- src/components/formcomponents/group/table/tables/table/__tests__/StandardTable-spec.tsx
- src/components/formcomponents/group/table/tables/table/__tests__/standartable-utils-spec.ts
- src/components/formcomponents/group/table/tables/table/utils.ts
> Rubenr/standard table bug - Tests

- preview/skjema/q.json
- src/components/formcomponents/date/date-day-input.tsx
- src/components/formcomponents/date/date-month-input.tsx
- src/components/formcomponents/date/date-year-input.tsx
- src/components/formcomponents/date/date.tsx
- Changes to the functionallity at date-day, not updating the qr before the date is a valid date
- Remove unused locale and only intialize locale at the top component
> dont update qr when date is not a valid date

- CHANGES.md
- package.json
- preview/skjema/q.json
- src/components/formcomponents/attachment/attachment.tsx
- src/components/formcomponents/attachment/useAttachmentSync.ts
add getId to add random ids to uploaded attachments
> use getId to set random ids on attachements

- src/calculators/runEnableWhen.ts
- src/components/formcomponents/group/table/tables/table/__tests__/standartable-utils-spec.ts
- src/reducers/form.ts
- Move logic for enableWhen into seperate file
- disable some tests
> move enableWhen to seperate file

- src/calculators/__tests__/scoringCalculators-spec.tsx
- src/components/__tests__/componentsWithChildren-spec.tsx
- src/components/__tests__/copy-from-spec.tsx
- src/components/__tests__/customButtons-spec.tsx
- src/components/__tests__/enableWhen-spec.tsx
- src/components/__tests__/group-grid-spec.tsx
- src/components/__tests__/group-spec.tsx
- src/components/__tests__/hidden-spec.tsx
- src/components/__tests__/markdown-spec.tsx
- src/components/formcomponents/boolean/__tests__/boolean-spec.tsx
- src/components/formcomponents/choice-common/__tests__/autosuggest-view-spec.tsx
- src/components/formcomponents/choice/__tests__/choice-slider-view-spec.tsx
- src/components/formcomponents/date/__tests__/date-day-spec.tsx
- src/components/formcomponents/date/__tests__/date-month-spec.tsx
- src/components/formcomponents/date/__tests__/date-time-spec.tsx
- src/components/formcomponents/date/__tests__/date-year-spec.tsx
- src/components/formcomponents/date/__tests__/time-spec.tsx
- src/components/formcomponents/decimal/__tests__/decimal-spec.tsx
- src/components/formcomponents/quantity/__tests__/quantity-spec.tsx
- src/components/formcomponents/string/__tests__/string-spec.tsx
- src/components/formcomponents/text/__tests__/text-spec.tsx
- Added webworker to prosess heavy form calculations in the background
- Fixed tests requiring act
> Release for v.19.0.0

- package-lock.json
- package.json
- sonar-report.xml
- src/components/formButtons/SubmitFormButton.tsx
- src/components/formButtons/formButtons.tsx
- update @helsenorge packages to latest major version
> update to core 36
